global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'vmetrics_local'

scrape_configs:
  - job_name: 'vmetrics_local'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9273',]
